name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: golang/govulncheck-action@v1.0.4
      - uses: securego/gosec@v2.26.1
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
